# Generated by Django 4.1.4 on 2023-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_results_correct_answer_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_pic',
            field=models.ImageField(default=True, height_field=30, upload_to='', width_field=30),
        ),
    ]
