# Generated by Django 4.1.4 on 2023-01-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_answer_answer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_pic',
            field=models.ImageField(default='default.jpg', height_field=30, upload_to='photos/answers', verbose_name='Фото ответа', width_field=30),
        ),
    ]
